name: news_us_tech
description: A News for tech

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_core: ^3.4.1
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  intl: 0.19.0
  retrofit: ^4.0.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6
  flutter_launcher_icons: "^0.13.1"
  test: ^1.25.7
  commitlint_cli: ^0.7.1
  husky: ^0.1.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/flutter_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/flutter_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/flutter_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/flutter_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
